/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import model.Autobus;
import model.Trolejbus;

/**
 *
 * @author GAZi
 */
public class TrolejbusDialog extends javax.swing.JDialog {

    private Trolejbus trolejbus = null;

    
    /**
     * Creates new form TrolejbusDialog
     */
    public TrolejbusDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Trolejbus getTrolejbus() {
        return trolejbus;
    }

    public void setTrolejbus(Trolejbus trolejbus) {
        this.trolejbus = trolejbus;
   
    rokVyrobyTextField.setText(String.valueOf(this.trolejbus.getRokVyroby()));
        kapacitaTextField.setText(String.valueOf(this.trolejbus.getKapacita()));
        evidencniCisloTextField.setText(String.valueOf(this.trolejbus.getEvidencniCislo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rokVyrobyLabel = new javax.swing.JLabel();
        kapacitaLabel = new javax.swing.JLabel();
        evidencniCisloLabel = new javax.swing.JLabel();
        rokVyrobyTextField = new javax.swing.JTextField();
        kapacitaTextField = new javax.swing.JTextField();
        evidencniCisloTextField = new javax.swing.JTextField();
        potvrdButton = new javax.swing.JButton();
        zrusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trolejbus");
        setModal(true);

        rokVyrobyLabel.setText("Rok výroby:");

        kapacitaLabel.setText("Kapacita:");

        evidencniCisloLabel.setText("Evidenční číslo:");

        potvrdButton.setText("OK");
        potvrdButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potvrdButtonMouseClicked(evt);
            }
        });

        zrusButton.setText("Zrušit");
        zrusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zrusButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evidencniCisloLabel)
                    .addComponent(kapacitaLabel)
                    .addComponent(rokVyrobyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rokVyrobyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(kapacitaTextField)
                    .addComponent(evidencniCisloTextField))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(potvrdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zrusButton)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rokVyrobyLabel)
                    .addComponent(rokVyrobyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kapacitaLabel)
                    .addComponent(kapacitaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evidencniCisloLabel)
                    .addComponent(evidencniCisloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potvrdButton)
                    .addComponent(zrusButton))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void potvrdButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potvrdButtonMouseClicked
        boolean ok = true;
        // tady by byli kontroly správnosti zadaných údajů
        // kdyz by bylo neco nevalidni, ok se nastavi na false
        // ok = false;

        if(!ok)
            return;

        if(this.trolejbus == null)
            this.trolejbus = new Trolejbus();

        this.trolejbus.setKapacita(Integer.parseInt(kapacitaTextField.getText()));
        this.trolejbus.setRokVyroby(Integer.parseInt(rokVyrobyTextField.getText()));
        this.trolejbus.setEvidencniCislo(Integer.parseInt(evidencniCisloTextField.getText()));

        this.setVisible(false);
    }//GEN-LAST:event_potvrdButtonMouseClicked

    private void zrusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zrusButtonMouseClicked
        this.trolejbus = null;

        this.setVisible(false);
    }//GEN-LAST:event_zrusButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrolejbusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrolejbusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrolejbusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrolejbusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrolejbusDialog dialog = new TrolejbusDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel evidencniCisloLabel;
    private javax.swing.JTextField evidencniCisloTextField;
    private javax.swing.JLabel kapacitaLabel;
    private javax.swing.JTextField kapacitaTextField;
    private javax.swing.JButton potvrdButton;
    private javax.swing.JLabel rokVyrobyLabel;
    private javax.swing.JTextField rokVyrobyTextField;
    private javax.swing.JButton zrusButton;
    // End of variables declaration//GEN-END:variables

    void setAutobus(Autobus autobus) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
